---
title: "Final Project"
description: |
   Final Project for Acc-8143/Accounting Data Analytics
date: "`r Sys.Date()`"
output: distill::distill_article
---

## Classification 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
Movies<-read.csv(file= 'Movies.csv')
```


```{r}
library(caret)
library(tidyverse)
set.seed(1)
```

```{r}
#lets split the data 60/40
library(caret)
trainIndex <- createDataPartition(iris$Species, p = .6, list = FALSE, times = 1)

#look at the first few
head(trainIndex)
```


```{r}
MoviesTrain <- Movies[ trainIndex,]
MoviesTest  <- Movies[-trainIndex,]
```

```{r}
preProcValues <- preProcess(MoviesTest, method = c("center", "scale"))
testTransformed <- predict(preProcValues, MoviesTest)
```



```{r}
psych::describe(MoviesTrain)
```

```{r}
psych::describe(testTransformed)
```

```{r}
knn_fit<-train(Movie.Title~.,
               data=testTransformed,
               method="knn",
               tuneGrid=data.frame(k=10))

knn_fit
```

```{r}
knn_pred<-predict(knn_fit,trainTransformed)
```

```{r}
confusionMatrix(knn_pred,trainTransformed$Species)
```

