---
title: "ML"
description: |
   Use one of your exercises to show off a machine learning model.
date: "`r Sys.Date()`"
output: distill::distill_article
---
#Data Pre-Processing 

- Explanation 



- Process and Results



- How it can be used in accounting 


```{r svm.ex.1.a}
library(caret)
library(tidyverse)
#set the seed :)
set.seed(1)
#get our samples
#using the iris data
#lets split the data 60/40

trainIndex <- createDataPartition(iris$Species, p = .75, list = FALSE, times = 1)

#look at the first few
#head(trainIndex)

#grab the data
SVMTrain <- iris[ trainIndex,]
SVMTest  <- iris[-trainIndex,]

iris_SVM <- train(
  form = factor(Species) ~ .,
  data = SVMTrain,
  #here we add classProbs because we want probs
  trControl = trainControl(method = "cv", number = 10,
                           classProbs =  TRUE),
  method = "svmLinear",
  preProcess = c("center", "scale"),
  tuneLength = 10)

iris_SVM

summary(iris_SVM)

svm_Pred<-predict(iris_SVM,SVMTest,type="prob")

svmtestpred<-cbind(svm_Pred,SVMTest)

svmtestpred<-svmtestpred%>%
  mutate(prediction=if_else(setosa>versicolor & setosa>virginica,"setosa",
  if_else(versicolor>setosa & versicolor>virginica, "versicolor",
  if_else(virginica>setosa & virginica>versicolor,"virginica", "PROBLEM"))))

table(svmtestpred$prediction)
confusionMatrix(factor(svmtestpred$prediction),factor(svmtestpred$Species))
```

```{r svm.ex.1.b}
library(caret)
library(tidyverse)
#set the seed :)
set.seed(1)
#get our samples
#using the iris data
#lets split the data 60/40

trainIndex <- createDataPartition(iris$Species, p = .50, list = FALSE, times = 1)

#look at the first few
#head(trainIndex)

#grab the data
SVMTrain <- iris[ trainIndex,]
SVMTest  <- iris[-trainIndex,]

iris_SVM <- train(
  form = factor(Species) ~ .,
  data = SVMTrain,
  #here we add classProbs because we want probs
  trControl = trainControl(method = "cv", number = 10,
                           classProbs =  TRUE),
  method = "svmLinear",
  preProcess = c("center", "scale"),
  tuneLength = 10)

iris_SVM

summary(iris_SVM)

svm_Pred<-predict(iris_SVM,SVMTest,type="prob")

svmtestpred<-cbind(svm_Pred,SVMTest)

svmtestpred<-svmtestpred%>%
  mutate(prediction=if_else(setosa>versicolor & setosa>virginica,"setosa",
  if_else(versicolor>setosa & versicolor>virginica, "versicolor",
  if_else(virginica>setosa & virginica>versicolor,"virginica", "PROBLEM"))))

table(svmtestpred$prediction)
confusionMatrix(factor(svmtestpred$prediction),factor(svmtestpred$Species))
```